name: Update Google Sheet

on:
  schedule:
    - cron: '0 * * * *' # Executar a cada hora
  workflow_dispatch: # Permite execução manual

jobs:
  update-sheet:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install gspread requests oauth2client pandas

    - name: Run update script
      run: |
        python dadosvendasbrabo.py
